spring:
#  profiles: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug

server:
  port: 7777
#  ssl:
#    enabled: true
#    key-store: keystore_dev.p12
#    key-store-password: Ga123!@#
#    key-store-type: PKCS12
#    key-alias: bns-ssl