spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1000MB
  #  profiles: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
  devtools:
    restart:
      exclude: images/**,masks/**,cache_data/**


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug

server:
  port: 7778
#  ssl:
#    enabled: true
#    key-store: keystore_dev.p12
#    key-store-password: Ga123!@#
#    key-store-type: PKCS12
#    key-alias: bns-ssl